<?php
/**
 * @file
 * Module file for the Estate content type.
 */

/**
 * Implements hook_preprocess_hook().
 */
function wang_estate_preprocess_page(&$variables) {
  $node = $variables['node'];

  if (!empty($node->type) && $node->type !== 'estate') {
    return;
  }

  $wre_path = drupal_get_path('theme', 'wangrealestate');
  $key = '?key=' . '';

  drupal_add_js('https://maps.googleapis.com/maps/api/js' . $key, array(
      'group' => JS_DEFAULT,
      'type' => 'external',
      'weight' => 0,
    )
  );
  drupal_add_js($wre_path . '/plugins/slick/slick.js', array(
      'group' => JS_DEFAULT,
      'type' => 'file',
      'weight' => 0,
    )
  );
  drupal_add_js(drupal_get_path('module', 'wang_estate') . '/js/wang_estate.js', array(
      'group' => JS_DEFAULT,
      'type' => 'file',
      'weight' => 0,
    )
  );
  drupal_add_css($wre_path . '/plugins/slick/slick.css',
    array(
      'group' => CSS_DEFAULT,
      'type' => 'file',
      'weight' => -2,
    )
  );
  drupal_add_css($wre_path . '/plugins/slick/slick-theme.css',
    array(
      'group' => CSS_DEFAULT,
      'type' => 'file',
      'weight' => -2,
    )
  );
}

/**
 * Implements hook_preprocess_hook().
 */
function wang_estate_preprocess_node(&$variables) {
  $node = $variables['node'];

  $variables['beds'] = get_field($node, 'field_bed');
  $variables['baths'] = get_field($node, 'field_bath');
  $variables['list_price'] = get_field($node, 'field_list_price');
  $variables['cost_sqft'] = get_field($node, 'field_cost_sqft');
  $variables['sqft'] = get_field($node, 'field_sqft');
  $variables['lot_size'] = get_field($node, 'field_lot_size');
  $variables['year_built'] = get_field($node, 'field_year_built');
  $variables['property_type'] = get_field($node, 'field_property_type');
  $variables['stories'] = get_field($node, 'field_stories');
  $variables['mls'] = get_field($node, 'field_mls');
  $variables['description'] = get_field($node, 'field_description');
  $variables['address'] = get_field($node, 'field_address');
  $variables['geolocation'] = get_field($node, 'field_geolocation');

  $images = get_field($node, 'field_image');
  $image_paths = array();
  foreach ($images as $key => $image) {
    $image_paths[] = file_create_url($image['uri']);
  }

  $variables['image_paths'] = $image_paths;
}

function get_field($node, $field_name, $entity_type = 'node') {
  if (!is_object($node)) {
    return;
  }

  $node_wrapper = entity_metadata_wrapper($entity_type, $node);

  return $node_wrapper->$field_name->value();
}