<?php
/**
 * @file
 * Module file for the Estate content type.
 */

/**
 * Implements hook_preprocess_hook().
 */
function wang_estate_preprocess_node(&$variables) {
  $node = $variables['node'];

  $variables['beds'] = get_field($node, 'field_bed');
  $variables['list_price'] = get_field($node, 'field_list_price');
  $variables['cost_sqft'] = get_field($node, 'field_cost_sqft');
  $variables['sqft'] = get_field($node, 'field_sqft');
  $variables['lot_size'] = get_field($node, 'field_lot_size');
  $variables['year_built'] = get_field($node, 'field_year_built');
  $variables['property_type'] = get_field($node, 'field_property_type');
  $variables['stories'] = get_field($node, 'field_stories');
  $variables['mls'] = get_field($node, 'field_mls');
  $variables['description'] = get_field($node, 'field_description');
  $variables['address'] = get_field($node, 'field_address');
  $variables['geolocation'] = get_field($node, 'field_bath');

  $images = get_field($node, 'field_image');
  $image_paths = array();
  foreach ($images as $key => $image) {
    $image_paths[] = file_create_url($image['uri']);
  }

  $variables['image_paths'] = $image_paths;
}

function get_field($node, $field_name, $entity_type = 'node') {
  if (!is_object($node)) {
    return;
  }

  $node_wrapper = entity_metadata_wrapper($entity_type, $node);

  return $node_wrapper->$field_name->value();
}